name:                haskell-chess-app
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/cApp1#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text
  - optics-core
  - optics-th
  - pipes
  - unagi-chan
  - async
  - gi-gtk
  - gi-gtk-declarative
  - gi-gtk-declarative-app-simple


executables:
  haskell-chess-app:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
      - -threaded
    default-extensions:
      - TupleSections
      - GADTs
      - OverloadedStrings
